### model
model_name_or_path: Qwen/Qwen2.5-Math-7B

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json
flash_attn: fa2
gradient_checkpointing: true

### dataset
dataset: openr1_20k
cutoff_len: 8192
overwrite_cache: true
preprocessing_num_workers: 64
template: qwen

### output
output_dir: /projects/ai_safe/cuongdc/open_r1/20k_self_data
logging_steps: 1
save_strategy: epoch
plot_loss: true
overwrite_output_dir: true
save_only_model: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 1
learning_rate: 5.0e-5
num_train_epochs: 10
lr_scheduler_type: cosine
warmup_ratio: 0.0
bf16: true
ddp_timeout: 180000000